#!/bin/bash
# Yee vortex, coherent beta(U*) GL+F1 total-residual RK2 experiment.
# Phi(U^n) is explicitly redistributed; the +dU/2 shortcut is disabled.

TWODIMS
GAMMA=1.4
READ_MASS_AS_DENSITY_IN_INPUT
VORONOI_STATIC_MESH

RESIDUAL_DISTRIBUTION
LDA_SCHEME
RD_DEBUG_ASSERTS
RD_RK2_TOTAL_RESIDUAL
RD_RK2_COHERENT_BETA_STAR

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS

HAVE_HDF5
DEBUG
