#!/bin/bash
# Phase-B two-level hierarchy with the bin interface displaced away from the
# vortex (split at x = 0.25 L instead of 0.5 L), to separate "the interface is
# defective" from "the interface crosses the only unsteady feature".

TWODIMS
GAMMA=1.4
READ_MASS_AS_DENSITY_IN_INPUT
VORONOI_STATIC_MESH
CREATE_FULL_MESH

RESIDUAL_DISTRIBUTION
N_SCHEME
RD_DEBUG_ASSERTS
RD_RK2_TOTAL_RESIDUAL
RD_HIERARCHICAL_TIMESTEPS
RD_HIERARCHICAL_TEST_PATTERN
RD_HIER_TEST_SPLIT_FRAC=0.25

TREE_BASED_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS
OUTPUT_TIMEBIN_HYDRO
OUTPUT_PRESSURE

HAVE_HDF5
DEBUG
