#!/bin/bash

# Yee vortex (gamma=1.4) moving-mesh LDA control, matched switch-for-switch
# to Config_YEE_con_cm_Bscalar.sh.  Modern equivalent of the section-33.2
# Y_contour campaign config (RD_LDA_COMOVING_FRAME is now
# RD_ELEMENT_COMOVING_FRAME).
TWODIMS
GAMMA=1.4
READ_MASS_AS_DENSITY_IN_INPUT

REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED
REGULARIZE_MESH_FACE_ANGLE

RESIDUAL_DISTRIBUTION
LDA_SCHEME
RD_RK2_TOTAL_RESIDUAL
RD_DEBUG_ASSERTS
RD_ALE_EQUALSTEP
RD_ALE_GEOMETRY_DIAGNOSTICS

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS
OUTPUT_TIMEBIN_HYDRO
OUTPUT_VERTEX_VELOCITY
OUTPUT_VOLUME
OUTPUT_PRESSURE

HAVE_HDF5
DEBUG
RD_ALE_CONTOUR_RESIDUAL
RD_ELEMENT_COMOVING_FRAME
RD_ALE_CFL_TIMESTEP
RD_ALE_CFL_DIAGNOSTIC
