#!/bin/bash

# Rigid free-stream translation: sigma=v, regularisation disabled.
TWODIMS
GAMMA=(5.0/3.0)
READ_MASS_AS_DENSITY_IN_INPUT

RESIDUAL_DISTRIBUTION
N_SCHEME
RD_RK2_TOTAL_RESIDUAL
RD_DEBUG_ASSERTS
RD_ALE_EQUALSTEP
RD_ALE_GEOMETRY_DIAGNOSTICS

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS
OUTPUT_TIMEBIN_HYDRO
OUTPUT_VERTEX_VELOCITY
OUTPUT_VOLUME
OUTPUT_PRESSURE

HAVE_HDF5
DEBUG
