#!/bin/bash

## Paired control for Config_ALE_Geometry_Stage0.sh: identical moving-mesh FV
## run, but with AREPO's mesh regularisation disabled.

TWODIMS
READ_MASS_AS_DENSITY_IN_INPUT

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

RD_ALE_GEOMETRY_DIAGNOSTICS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS

HAVE_HDF5
DEBUG
