#!/bin/bash
# Gamma-1.4 N scheme: Arpaia mass, contour residual, element co-moving frame.
# Shared by the small Sod, KH, and Yee moving-mesh regression campaign.

TWODIMS
GAMMA=1.4
READ_MASS_AS_DENSITY_IN_INPUT

REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED
REGULARIZE_MESH_FACE_ANGLE

RESIDUAL_DISTRIBUTION
N_SCHEME
RD_RK2_TOTAL_RESIDUAL
RD_DEBUG_ASSERTS
RD_ALE_EQUALSTEP
RD_ALE_GEOMETRY_DIAGNOSTICS

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS
OUTPUT_TIMEBIN_HYDRO
OUTPUT_VERTEX_VELOCITY
OUTPUT_VOLUME
OUTPUT_PRESSURE

HAVE_HDF5
DEBUG
RD_ALE_CONTOUR_RESIDUAL
RD_ELEMENT_COMOVING_FRAME
RD_ALE_CFL_TIMESTEP
RD_ALE_CFL_DIAGNOSTIC
