#!/bin/bash

# Yee vortex (gamma=1.4) moving-mesh scalar-B convergence arm.
# Config_F_con_cm_B.sh with GAMMA=1.4; contour total, element co-moving frame,
# scalar-theta frozen-theta B blend, f=1.  Experimental, not a default.
TWODIMS
GAMMA=1.4
READ_MASS_AS_DENSITY_IN_INPUT

REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED
REGULARIZE_MESH_FACE_ANGLE

RESIDUAL_DISTRIBUTION
B_SCHEME
RD_RK2_TOTAL_RESIDUAL
RD_B_FROZEN_THETA
RD_B_SCALAR_THETA
RD_DIAG_THETA
RD_DEBUG_ASSERTS
RD_ALE_EQUALSTEP
RD_ALE_GEOMETRY_DIAGNOSTICS

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS
OUTPUT_TIMEBIN_HYDRO
OUTPUT_VERTEX_VELOCITY
OUTPUT_VOLUME
OUTPUT_PRESSURE

HAVE_HDF5
DEBUG
RD_ALE_CONTOUR_RESIDUAL
RD_ELEMENT_COMOVING_FRAME
RD_ALE_CFL_TIMESTEP
RD_ALE_CFL_DIAGNOSTIC
