#!/bin/bash

## Diagnostic-only Stage-0 ALE geometry run.  The finite-volume solver drives
## the real AREPO mesh motion; rd_ale_geometry_diagnostics.c only observes it.

TWODIMS
READ_MASS_AS_DENSITY_IN_INPUT

REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED
REGULARIZE_MESH_FACE_ANGLE

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

RD_ALE_GEOMETRY_DIAGNOSTICS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS

HAVE_HDF5
DEBUG
