#!/bin/bash
# SWIFT/Saitoh-Makino-style Rayleigh--Taylor pilot with a prescribed constant
# downward acceleration.  The y walls replace SWIFT's fixed boundary particles;
# their compatibility with RD is an explicit gate of this experiment.
TWODIMS
LONG_Y=1.5
REFLECTIVE_Y=1
GAMMA=1.4
READ_MASS_AS_DENSITY_IN_INPUT
VORONOI_STATIC_MESH
CREATE_FULL_MESH

RESIDUAL_DISTRIBUTION
N_SCHEME
RD_DEBUG_ASSERTS
RD_RK2_TOTAL_RESIDUAL

EXTERNALGRAVITY
EXTERNALGY=-0.5
EVALPOTENTIAL
OUTPUTACCELERATION

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS
OUTPUT_TIMEBIN_HYDRO
OUTPUT_PRESSURE
HAVE_HDF5
DEBUG
