#!/bin/bash
# Morton et al. (2023), Fig. 7: static pseudo-1D first-order LDA control.

TWODIMS
GAMMA=(5.0/3.0)
READ_MASS_AS_DENSITY_IN_INPUT
VORONOI_STATIC_MESH

RESIDUAL_DISTRIBUTION
LDA_SCHEME
RD_RK2_TOTAL_RESIDUAL
RD_DEBUG_ASSERTS

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS
OUTPUT_TIMEBIN_HYDRO
OUTPUT_VOLUME
OUTPUT_PRESSURE

HAVE_HDF5
DEBUG
