#!/bin/bash
# Equal-bin control for the Sod hierarchy test.

# N+RK2 path before mixed bins are enabled.

TWODIMS
GAMMA=1.4
READ_MASS_AS_DENSITY_IN_INPUT
VORONOI_STATIC_MESH
CREATE_FULL_MESH

RESIDUAL_DISTRIBUTION
N_SCHEME
RD_DEBUG_ASSERTS
RD_RK2_TOTAL_RESIDUAL
RD_HIERARCHICAL_TIMESTEPS

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS
OUTPUT_TIMEBIN_HYDRO
OUTPUT_PRESSURE

HAVE_HDF5
DEBUG
