#!/bin/bash
# 2-D periodic Sod with a bin interface the shock crosses. Fine region x < 0.85 L,
# so the right-going shock (speed 1.75 from x = 7.5) crosses x = 8.5 at t = 0.57 and
# the contact at t = 1.08.

TWODIMS
GAMMA=1.4
READ_MASS_AS_DENSITY_IN_INPUT
VORONOI_STATIC_MESH
CREATE_FULL_MESH

RESIDUAL_DISTRIBUTION
N_SCHEME
RD_DEBUG_ASSERTS
RD_RK2_TOTAL_RESIDUAL
RD_HIERARCHICAL_TIMESTEPS
RD_HIERARCHICAL_TEST_PATTERN
RD_HIER_TEST_SPLIT_FRAC=0.85

TREE_BASED_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS
OUTPUT_TIMEBIN_HYDRO
OUTPUT_PRESSURE

HAVE_HDF5
DEBUG
