#!/usr/bin/env python3
"""Prepare the matched-glass moving-N Sod 2x2x2 factorial campaign.

The factors are element total (Roe+split or contour), algebraic frame
(laboratory or element co-moving), and ALE nodal mass (Arpaia or Campoli).
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import shutil
from pathlib import Path

from prepare_glass_sod_kh import render


BASE_CONFIG = """#!/bin/bash
# Generated by prepare_sod_n_factorial.py: matched moving-N Sod factorial.
TWODIMS
GAMMA=(5.0/3.0)
READ_MASS_AS_DENSITY_IN_INPUT

REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED
REGULARIZE_MESH_FACE_ANGLE

RESIDUAL_DISTRIBUTION
N_SCHEME
RD_RK2_TOTAL_RESIDUAL
RD_DEBUG_ASSERTS
RD_ALE_EQUALSTEP
RD_ALE_GEOMETRY_DIAGNOSTICS

TREE_BASED_TIMESTEPS
FORCE_EQUAL_TIMESTEPS

DOUBLEPRECISION=1
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_CENTER_OF_MASS
OUTPUT_TIMEBIN_HYDRO
OUTPUT_VERTEX_VELOCITY
OUTPUT_VOLUME
OUTPUT_PRESSURE

HAVE_HDF5
DEBUG
RD_ALE_CFL_TIMESTEP
RD_ALE_CFL_DIAGNOSTIC
"""


def digest(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            value.update(block)
    return value.hexdigest()


def variant_name(residual: str, frame: str, mass: str) -> str:
    return f"N_{residual}_{frame}_{mass}"


def config_text(residual: str, frame: str, mass: str) -> str:
    flags = []
    if residual == "roe_split":
        flags.append("RD_ALE_SPLIT_MESH_VELOCITY")
    elif residual == "contour":
        flags.append("RD_ALE_CONTOUR_RESIDUAL")
    else:
        raise ValueError(residual)
    if frame == "comoving":
        flags.append("RD_ELEMENT_COMOVING_FRAME")
    elif frame != "lab":
        raise ValueError(frame)
    if mass == "campoli":
        flags.append("RD_ALE_CAMPOLI_MASS")
    elif mass != "arpaia":
        raise ValueError(mass)
    return BASE_CONFIG + "\n".join(flags) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", type=Path)
    parser.add_argument("--ic", required=True, type=Path)
    parser.add_argument("--param-template", required=True, type=Path)
    args = parser.parse_args()

    root = args.root.resolve()
    source_ic = args.ic.resolve()
    template_path = args.param_template.resolve()
    if root.exists() and any(root.iterdir()):
        raise SystemExit(f"refusing to modify non-empty campaign root: {root}")
    if not source_ic.is_file() or not template_path.is_file():
        raise SystemExit("IC and parameter template must both exist")

    root.mkdir(parents=True, exist_ok=True)
    input_dir = root / "inputs"
    config_dir = root / "configs"
    runs_dir = root / "runs"
    input_dir.mkdir()
    config_dir.mkdir()
    runs_dir.mkdir()

    target_ic = input_dir / "IC_sod_glass48.hdf5"
    shutil.copy2(source_ic, target_ic)
    template = template_path.read_text()
    cases = []
    for residual, frame, mass in itertools.product(
        ("roe_split", "contour"), ("lab", "comoving"), ("arpaia", "campoli")
    ):
        variant = variant_name(residual, frame, mass)
        config = config_dir / f"Config_{variant}.sh"
        config.write_text(config_text(residual, frame, mass))

        case_dir = runs_dir / variant
        output_dir = case_dir / "output"
        output_dir.mkdir(parents=True)
        param = case_dir / "param.txt"
        replacements = {
            "InitCondFile": str(target_ic.with_suffix("")),
            "OutputDir": str(output_dir) + "/",
            "BoxSize": "2",
            "TimeOfFirstSnapshot": "0",
            "TimeMax": "0.2",
            "TimeBetSnapshot": "0.01",
            "TimeBetStatistics": "0.01",
            "MaxSizeTimestep": "0.02",
            "MinSizeTimestep": "1e-8",
            "CourantFac": "0.4",
        }
        param.write_text(render(template, replacements))
        cases.append(
            {
                "variant": variant,
                "residual": residual,
                "frame": frame,
                "mass": mass,
                "config": str(config),
                "config_sha256": digest(config),
                "param": str(param),
                "param_sha256": digest(param),
                "output": str(output_dir),
            }
        )

    manifest = {
        "description": "Moving N-RK2 Sod 2x2x2: residual x frame x ALE mass",
        "mesh_family": "relaxed periodic SWIFT glass48",
        "cells": 2304,
        "ic": str(target_ic),
        "ic_sha256": digest(target_ic),
        "matched_ic_and_runtime_parameters": True,
        "snapshot_interval": 0.01,
        "time_max": 0.2,
        "cases": cases,
    }
    (root / "campaign.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"prepared {len(cases)} cases under {root}")


if __name__ == "__main__":
    main()
